In [1]:
import torch
from unsloth import FastLanguageModel
import src.config as config
from src.train.lora_train import train_model
from src.train.sgd_full_train import train_model_sgd
from src.train.train_pipeline import train_pipeline
from src.data.prompt import mbpp
from src.data.prompt import openthoughts
from src.data.prompt import pythoncodes
from huggingface_hub import snapshot_download

import gc

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
WARNING 02-21 19:39:06 [interface.py:409] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
🦥 Unsloth Zoo will now patch everything to make training faster!

In [2]:
snapshot_download(
    repo_id=config.MODEL_NAME,
    local_dir=config.MODEL_PATH,
    local_dir_use_symlinks=False,
    resume_download=True
)

'/workspace/models/qwen3-0.6b'

In [3]:
def run_experiments(experiments, skip_n):
	for i, (experiment_name, use_lora, exp) in enumerate(experiments):
		if skip_n > 0:
			skip_n -= 1
			continue

		print(f"=== Experiment {i+1}/{len(experiments)}: {experiment_name} ===")

		gc.collect()
		torch.cuda.empty_cache()

		path = config.MODEL_PATH + ("-sft" if use_lora == "lora" else "-sgd") + f"-{i+1}-exp"
		model, tokenizer = train_pipeline(exp, use_lora=use_lora, save_path=path)
	return model, tokenizer

In [4]:
experiments = [
	(
		"Double Training (LoRA)", "lora",
		[
			("Openthoughts-114k", openthoughts.get_prepared_dataset, {
				"lr": 2e-4,
				"batch_size": 4,
				"gradient_steps": 4,
				"max_steps": 500,
				"warmup_steps": 25,
				"optim": "paged_adamw_8bit",
				"assistant_only_loss": True,
			}),
			("Pythoncodes", pythoncodes.get_prepared_dataset, {
				"lr": 2e-5,
				"batch_size": 8,
				"gradient_steps": 8,
				"max_steps": 500,
				"warmup_steps": 25,
				"optim": "paged_adamw_8bit",
				"assistant_only_loss": True,
			}),
		]
	),
	(
		"Double Training (Full Train)", "full_train",
		[
			("Openthoughts-114k", openthoughts.get_prepared_dataset, {
				"lr": 3e-6,
				"batch_size": 4,
				"gradient_steps": 4,
				"max_steps": 500,
				"warmup_steps": 25,
				"optim": "paged_adamw_8bit",
				"assistant_only_loss": True,
			}),
			("Pythoncodes", pythoncodes.get_prepared_dataset, {
				"lr": 4e-7,
				"batch_size": 8,
				"gradient_steps": 8,
				"max_steps": 500,
				"warmup_steps": 25,
				"optim": "paged_adamw_8bit",
				"assistant_only_loss": True,
			}),
		]
	),
	(
		"Inverse Double Training (LoRA)", "lora",
		[
			("Pythoncodes", pythoncodes.get_prepared_dataset, {
				"lr": 1e-4,
				"batch_size": 8,
				"gradient_steps": 8,
				"max_steps": 500,
				"warmup_steps": 25,
				"optim": "paged_adamw_8bit",
				"assistant_only_loss": True,
			}),
			("Openthoughts-114k", openthoughts.get_prepared_dataset, {
				"lr": 3e-5,
				"batch_size": 4,
				"gradient_steps": 4,
				"max_steps": 500,
				"warmup_steps": 25,
				"optim": "paged_adamw_8bit",
				"assistant_only_loss": True,
			}),
		]
	),
	(
		"Inverse Double Training (Full Train)", "full_train",
		[
			("Pythoncodes", pythoncodes.get_prepared_dataset, {
				"lr": 1e-5,
				"batch_size": 8,
				"gradient_steps": 8,
				"max_steps": 500,
				"warmup_steps": 25,
				"optim": "paged_adamw_8bit",
				"assistant_only_loss": True,
			}),
			("Openthoughts-114k", openthoughts.get_prepared_dataset, {
				"lr": 3e-7,
				"batch_size": 4,
				"gradient_steps": 4,
				"max_steps": 500,
				"warmup_steps": 25,
				"optim": "paged_adamw_8bit",
				"assistant_only_loss": True,
			}),
		]
	),
	(
		"OpenThoughts (LoRA)", "lora",
		[
			("Openthoughts-114k", openthoughts.get_prepared_dataset, {
				"lr": 3e-6,
				"batch_size": 4,
				"gradient_steps": 4,
				"max_steps": 500,
				"warmup_steps": 25,
				"optim": "paged_adamw_8bit",
				"assistant_only_loss": True,
			}),
		]
	),
	(
		"OpenThoughts (Full Train)", "full_train",
		[
			("Openthoughts-114k", openthoughts.get_prepared_dataset, {
				"lr": 3e-7,
				"batch_size": 4,
				"gradient_steps": 4,
				"max_steps": 500,
				"warmup_steps": 25,
				"optim": "paged_adamw_8bit",
				"assistant_only_loss": True,
			}),
		]
	),
	(
		"Pythoncodes (LoRA)", "lora",
		[
			("Pythoncodes", pythoncodes.get_prepared_dataset, {
				"lr": 3e-6,
				"batch_size": 8,
				"gradient_steps": 8,
				"max_steps": 500,
				"warmup_steps": 25,
				"optim": "paged_adamw_8bit",
				"assistant_only_loss": True,
			}),
		]
	),
	(
		"Pythoncodes (Full Train)", "full_train",
		[
			("Pythoncodes", pythoncodes.get_prepared_dataset, {
				"lr": 3e-7,
				"batch_size": 8,
				"gradient_steps": 8,
				"max_steps": 500,
				"warmup_steps": 25,
				"optim": "paged_adamw_8bit",
				"assistant_only_loss": True,
			}),
		]
	),
]

In [5]:
model, tokenizer = run_experiments(experiments, skip_n=0)
FastLanguageModel.for_inference(model=model)

=== Experiment 1/8: Double Training (LoRA) ===
19:39:11 | INFO | === Запуск этапа 1/2: Openthoughts-114k ===
19:39:11 | INFO | Загрузка базовой модели ./models/qwen3-0.6b...
==((====))==  Unsloth 2026.1.2: Fast Qwen3 patching. Transformers: 4.57.1. vLLM: 0.11.2.
   \\   /|    NVIDIA GeForce RTX 4070 Ti SUPER. Num GPUs = 1. Max memory: 15.992 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu128. CUDA: 8.9. CUDA Toolkit: 12.8. Triton: 3.5.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
19:39:26 | INFO | Инициализация PEFT/LoRA адаптеров...

Unsloth 2026.1.2 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.

19:39:30 | INFO | Составляем датасет для Openthoughts-114k...
19:39:32 | INFO | Берем 8000 примеров из IterableDataset.

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/8000 [00:00<?, ? examples/s]

19:44:16 | INFO | Начинаем обучение на Openthoughts-114k (Оптимизатор: paged_adamw_8bit)...

The model is already on multiple devices. Skipping the move to device specified in `args`.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 8,000 | Num Epochs = 1 | Total steps = 500
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 4 x 1) = 16
 "-____-"     Trainable parameters = 20,185,088 of 616,235,008 (3.28% trained)

Unsloth: Will smartly offload gradients to save VRAM!

19:57:15 | INFO | === Запуск этапа 2/2: Pythoncodes ===
19:57:15 | INFO | Модель уже загружена, продолжаем пайплайн...
19:57:15 | INFO | Составляем датасет для Pythoncodes...
19:57:20 | INFO | Начинаем обучение на Pythoncodes (Оптимизатор: paged_adamw_8bit)...

The model is already on multiple devices. Skipping the move to device specified in `args`.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 32,000 | Num Epochs = 9,223,372,036,854,775,807 | Total steps = 500
O^O/ \_/ \    Batch size per device = 8 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (8 x 8 x 1) = 64
 "-____-"     Trainable parameters = 20,185,088 of 616,235,008 (3.28% trained)
Too many dataloader workers: 4 (max is dataset.num_shards=2). Stopping 2 dataloader workers.
[datasets.iterable_dataset|WARNING]Too many dataloader workers: 4 (max is dataset.num_shards=2). Stopping 2 dataloader workers.

Unsloth: Will smartly offload gradients to save VRAM!

20:16:13 | INFO | Сохраняем объединенную модель в ./models/qwen3-0.6b-sft-1-exp...
20:16:13 | INFO | Все этапы пайплайна успешно завершены!
=== Experiment 2/8: Double Training (Full Train) ===
20:16:13 | INFO | === Запуск этапа 1/2: Openthoughts-114k ===
20:16:13 | INFO | Загрузка базовой модели ./models/qwen3-0.6b...
==((====))==  Unsloth 2026.1.2: Fast Qwen3 patching. Transformers: 4.57.1. vLLM: 0.11.2.
   \\   /|    NVIDIA GeForce RTX 4070 Ti SUPER. Num GPUs = 1. Max memory: 15.992 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu128. CUDA: 8.9. CUDA Toolkit: 12.8. Triton: 3.5.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
20:16:27 | INFO | Инициализация PEFT/LoRA адаптеров...
20:16:31 | INFO | Составляем датасет для Openthoughts-114k...
20:16:33 | INFO | Берем 8000 примеров из IterableDataset.

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/8000 [00:00<?, ? examples/s]

20:21:33 | INFO | Начинаем обучение на Openthoughts-114k (Оптимизатор: paged_adamw_8bit)...

The model is already on multiple devices. Skipping the move to device specified in `args`.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 8,000 | Num Epochs = 1 | Total steps = 500
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 4 x 1) = 16
 "-____-"     Trainable parameters = 20,185,088 of 616,235,008 (3.28% trained)

Unsloth: Will smartly offload gradients to save VRAM!

20:34:21 | INFO | === Запуск этапа 2/2: Pythoncodes ===
20:34:21 | INFO | Модель уже загружена, продолжаем пайплайн...
20:34:21 | INFO | Составляем датасет для Pythoncodes...
20:34:25 | INFO | Начинаем обучение на Pythoncodes (Оптимизатор: paged_adamw_8bit)...

The model is already on multiple devices. Skipping the move to device specified in `args`.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 32,000 | Num Epochs = 9,223,372,036,854,775,807 | Total steps = 500
O^O/ \_/ \    Batch size per device = 8 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (8 x 8 x 1) = 64
 "-____-"     Trainable parameters = 20,185,088 of 616,235,008 (3.28% trained)
Too many dataloader workers: 4 (max is dataset.num_shards=2). Stopping 2 dataloader workers.
[datasets.iterable_dataset|WARNING]Too many dataloader workers: 4 (max is dataset.num_shards=2). Stopping 2 dataloader workers.

Unsloth: Will smartly offload gradients to save VRAM!

20:51:38 | INFO | Сохраняем объединенную модель в ./models/qwen3-0.6b-sgd-2-exp...
20:51:39 | INFO | Все этапы пайплайна успешно завершены!
=== Experiment 3/8: Inverse Double Training (LoRA) ===
20:51:39 | INFO | === Запуск этапа 1/2: Pythoncodes ===
20:51:39 | INFO | Загрузка базовой модели ./models/qwen3-0.6b...
==((====))==  Unsloth 2026.1.2: Fast Qwen3 patching. Transformers: 4.57.1. vLLM: 0.11.2.
   \\   /|    NVIDIA GeForce RTX 4070 Ti SUPER. Num GPUs = 1. Max memory: 15.992 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu128. CUDA: 8.9. CUDA Toolkit: 12.8. Triton: 3.5.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
20:51:53 | INFO | Инициализация PEFT/LoRA адаптеров...
20:51:57 | INFO | Составляем датасет для Pythoncodes...
20:52:01 | INFO | Начинаем обучение на Pythoncodes (Оптимизатор: paged_adamw_8bit)...

The model is already on multiple devices. Skipping the move to device specified in `args`.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 32,000 | Num Epochs = 9,223,372,036,854,775,807 | Total steps = 500
O^O/ \_/ \    Batch size per device = 8 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (8 x 8 x 1) = 64
 "-____-"     Trainable parameters = 20,185,088 of 616,235,008 (3.28% trained)
Too many dataloader workers: 4 (max is dataset.num_shards=2). Stopping 2 dataloader workers.
[datasets.iterable_dataset|WARNING]Too many dataloader workers: 4 (max is dataset.num_shards=2). Stopping 2 dataloader workers.

Unsloth: Will smartly offload gradients to save VRAM!

21:09:11 | INFO | === Запуск этапа 2/2: Openthoughts-114k ===
21:09:11 | INFO | Модель уже загружена, продолжаем пайплайн...
21:09:11 | INFO | Составляем датасет для Openthoughts-114k...
21:09:13 | INFO | Берем 8000 примеров из IterableDataset.

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/8000 [00:00<?, ? examples/s]

21:13:58 | INFO | Начинаем обучение на Openthoughts-114k (Оптимизатор: paged_adamw_8bit)...

The model is already on multiple devices. Skipping the move to device specified in `args`.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 8,000 | Num Epochs = 1 | Total steps = 500
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 4 x 1) = 16
 "-____-"     Trainable parameters = 20,185,088 of 616,235,008 (3.28% trained)

Unsloth: Will smartly offload gradients to save VRAM!

21:26:09 | INFO | Сохраняем объединенную модель в ./models/qwen3-0.6b-sft-3-exp...
21:26:10 | INFO | Все этапы пайплайна успешно завершены!
=== Experiment 4/8: Inverse Double Training (Full Train) ===
21:26:10 | INFO | === Запуск этапа 1/2: Pythoncodes ===
21:26:10 | INFO | Загрузка базовой модели ./models/qwen3-0.6b...
==((====))==  Unsloth 2026.1.2: Fast Qwen3 patching. Transformers: 4.57.1. vLLM: 0.11.2.
   \\   /|    NVIDIA GeForce RTX 4070 Ti SUPER. Num GPUs = 1. Max memory: 15.992 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu128. CUDA: 8.9. CUDA Toolkit: 12.8. Triton: 3.5.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
21:26:23 | INFO | Инициализация PEFT/LoRA адаптеров...
21:26:28 | INFO | Составляем датасет для Pythoncodes...
21:26:32 | INFO | Начинаем обучение на Pythoncodes (Оптимизатор: paged_adamw_8bit)...

The model is already on multiple devices. Skipping the move to device specified in `args`.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 32,000 | Num Epochs = 9,223,372,036,854,775,807 | Total steps = 500
O^O/ \_/ \    Batch size per device = 8 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (8 x 8 x 1) = 64
 "-____-"     Trainable parameters = 20,185,088 of 616,235,008 (3.28% trained)
Too many dataloader workers: 4 (max is dataset.num_shards=2). Stopping 2 dataloader workers.
[datasets.iterable_dataset|WARNING]Too many dataloader workers: 4 (max is dataset.num_shards=2). Stopping 2 dataloader workers.

Unsloth: Will smartly offload gradients to save VRAM!

21:43:36 | INFO | === Запуск этапа 2/2: Openthoughts-114k ===
21:43:36 | INFO | Модель уже загружена, продолжаем пайплайн...
21:43:36 | INFO | Составляем датасет для Openthoughts-114k...
21:43:37 | INFO | Берем 8000 примеров из IterableDataset.

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/8000 [00:00<?, ? examples/s]

21:48:53 | INFO | Начинаем обучение на Openthoughts-114k (Оптимизатор: paged_adamw_8bit)...

The model is already on multiple devices. Skipping the move to device specified in `args`.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 8,000 | Num Epochs = 1 | Total steps = 500
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 4 x 1) = 16
 "-____-"     Trainable parameters = 20,185,088 of 616,235,008 (3.28% trained)

Unsloth: Will smartly offload gradients to save VRAM!

22:01:43 | INFO | Сохраняем объединенную модель в ./models/qwen3-0.6b-sgd-4-exp...
22:01:44 | INFO | Все этапы пайплайна успешно завершены!
=== Experiment 5/8: OpenThoughts (LoRA) ===
22:01:44 | INFO | === Запуск этапа 1/1: Openthoughts-114k ===
22:01:44 | INFO | Загрузка базовой модели ./models/qwen3-0.6b...
==((====))==  Unsloth 2026.1.2: Fast Qwen3 patching. Transformers: 4.57.1. vLLM: 0.11.2.
   \\   /|    NVIDIA GeForce RTX 4070 Ti SUPER. Num GPUs = 1. Max memory: 15.992 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu128. CUDA: 8.9. CUDA Toolkit: 12.8. Triton: 3.5.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
22:01:58 | INFO | Инициализация PEFT/LoRA адаптеров...
22:02:02 | INFO | Составляем датасет для Openthoughts-114k...
22:02:04 | INFO | Берем 8000 примеров из IterableDataset.

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/8000 [00:00<?, ? examples/s]

22:07:23 | INFO | Начинаем обучение на Openthoughts-114k (Оптимизатор: paged_adamw_8bit)...

The model is already on multiple devices. Skipping the move to device specified in `args`.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 8,000 | Num Epochs = 1 | Total steps = 500
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 4 x 1) = 16
 "-____-"     Trainable parameters = 20,185,088 of 616,235,008 (3.28% trained)

Unsloth: Will smartly offload gradients to save VRAM!

22:19:42 | INFO | Сохраняем объединенную модель в ./models/qwen3-0.6b-sft-5-exp...
22:19:42 | INFO | Все этапы пайплайна успешно завершены!
=== Experiment 6/8: OpenThoughts (Full Train) ===
22:19:43 | INFO | === Запуск этапа 1/1: Openthoughts-114k ===
22:19:43 | INFO | Загрузка базовой модели ./models/qwen3-0.6b...
==((====))==  Unsloth 2026.1.2: Fast Qwen3 patching. Transformers: 4.57.1. vLLM: 0.11.2.
   \\   /|    NVIDIA GeForce RTX 4070 Ti SUPER. Num GPUs = 1. Max memory: 15.992 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu128. CUDA: 8.9. CUDA Toolkit: 12.8. Triton: 3.5.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
22:19:56 | INFO | Инициализация PEFT/LoRA адаптеров...
22:20:00 | INFO | Составляем датасет для Openthoughts-114k...
22:20:02 | INFO | Берем 8000 примеров из IterableDataset.

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/8000 [00:00<?, ? examples/s]

22:24:55 | INFO | Начинаем обучение на Openthoughts-114k (Оптимизатор: paged_adamw_8bit)...

The model is already on multiple devices. Skipping the move to device specified in `args`.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 8,000 | Num Epochs = 1 | Total steps = 500
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 4 x 1) = 16
 "-____-"     Trainable parameters = 20,185,088 of 616,235,008 (3.28% trained)

Unsloth: Will smartly offload gradients to save VRAM!

22:37:10 | INFO | Сохраняем объединенную модель в ./models/qwen3-0.6b-sgd-6-exp...
22:37:10 | INFO | Все этапы пайплайна успешно завершены!
=== Experiment 7/8: Pythoncodes (LoRA) ===
22:37:11 | INFO | === Запуск этапа 1/1: Pythoncodes ===
22:37:11 | INFO | Загрузка базовой модели ./models/qwen3-0.6b...
==((====))==  Unsloth 2026.1.2: Fast Qwen3 patching. Transformers: 4.57.1. vLLM: 0.11.2.
   \\   /|    NVIDIA GeForce RTX 4070 Ti SUPER. Num GPUs = 1. Max memory: 15.992 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu128. CUDA: 8.9. CUDA Toolkit: 12.8. Triton: 3.5.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
22:37:25 | INFO | Инициализация PEFT/LoRA адаптеров...
22:37:29 | INFO | Составляем датасет для Pythoncodes...
22:37:34 | INFO | Начинаем обучение на Pythoncodes (Оптимизатор: paged_adamw_8bit)...

The model is already on multiple devices. Skipping the move to device specified in `args`.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 32,000 | Num Epochs = 9,223,372,036,854,775,807 | Total steps = 500
O^O/ \_/ \    Batch size per device = 8 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (8 x 8 x 1) = 64
 "-____-"     Trainable parameters = 20,185,088 of 616,235,008 (3.28% trained)
Too many dataloader workers: 4 (max is dataset.num_shards=2). Stopping 2 dataloader workers.
[datasets.iterable_dataset|WARNING]Too many dataloader workers: 4 (max is dataset.num_shards=2). Stopping 2 dataloader workers.

Unsloth: Will smartly offload gradients to save VRAM!

22:54:34 | INFO | Сохраняем объединенную модель в ./models/qwen3-0.6b-sft-7-exp...
22:54:35 | INFO | Все этапы пайплайна успешно завершены!
=== Experiment 8/8: Pythoncodes (Full Train) ===
22:54:35 | INFO | === Запуск этапа 1/1: Pythoncodes ===
22:54:35 | INFO | Загрузка базовой модели ./models/qwen3-0.6b...
==((====))==  Unsloth 2026.1.2: Fast Qwen3 patching. Transformers: 4.57.1. vLLM: 0.11.2.
   \\   /|    NVIDIA GeForce RTX 4070 Ti SUPER. Num GPUs = 1. Max memory: 15.992 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu128. CUDA: 8.9. CUDA Toolkit: 12.8. Triton: 3.5.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
22:54:48 | INFO | Инициализация PEFT/LoRA адаптеров...
22:54:53 | INFO | Составляем датасет для Pythoncodes...
22:54:57 | INFO | Начинаем обучение на Pythoncodes (Оптимизатор: paged_adamw_8bit)...

The model is already on multiple devices. Skipping the move to device specified in `args`.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 32,000 | Num Epochs = 9,223,372,036,854,775,807 | Total steps = 500
O^O/ \_/ \    Batch size per device = 8 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (8 x 8 x 1) = 64
 "-____-"     Trainable parameters = 20,185,088 of 616,235,008 (3.28% trained)
Too many dataloader workers: 4 (max is dataset.num_shards=2). Stopping 2 dataloader workers.
[datasets.iterable_dataset|WARNING]Too many dataloader workers: 4 (max is dataset.num_shards=2). Stopping 2 dataloader workers.

Unsloth: Will smartly offload gradients to save VRAM!

23:12:49 | INFO | Сохраняем объединенную модель в ./models/qwen3-0.6b-sgd-8-exp...
23:12:49 | INFO | Все этапы пайплайна успешно завершены!

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): Qwen3ForCausalLM(
      (model): Qwen3Model(
        (embed_tokens): Embedding(151936, 1024, padding_idx=151643)
        (layers): ModuleList(
          (0-27): 28 x Qwen3DecoderLayer(
            (self_attn): Qwen3Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=1024, out_features=2048, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1024, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=2048, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=1024, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1024, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=1024, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1024, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=2048, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2048, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen3MLP(
              (gate_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=1024, out_features=3072, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1024, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=3072, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=1024, out_features=3072, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1024, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=3072, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=3072, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=3072, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLUActivation()
            )
            (input_layernorm): Qwen3RMSNorm((1024,), eps=1e-06)
            (post_attention_layernorm): Qwen3RMSNorm((1024,), eps=1e-06)
          )
        )
        (norm): Qwen3RMSNorm((1024,), eps=1e-06)
        (rotary_emb): LlamaRotaryEmbedding()
      )
      (lm_head): Linear(in_features=1024, out_features=151936, bias=False)
    )
  )
)

In [6]:
def quick_sanity_check(model, tokenizer, prompt):
    print(f"🧐 Проверяем промпт: {prompt[:50]}...")

    inputs = tokenizer([prompt], return_tensors="pt").to("cuda")

    gen_kwargs = config.SAMPLING_SETTINGS.copy()
    gen_kwargs.update({
        "temperature": 0.6,
        "do_sample": True,
        "max_new_tokens": config.MAX_TOKENS,
        "num_return_sequences": 1,
    })

    if "n" in gen_kwargs:
        gen_kwargs["num_return_sequences"] = gen_kwargs.pop("n")

    for key in ["logprobs", "stop", "ignore_eos", "detokenize"]:
        gen_kwargs.pop(key, None)

    if "max_tokens" in gen_kwargs:
        gen_kwargs["max_new_tokens"] = gen_kwargs.pop("max_tokens")

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            pad_token_id=tokenizer.eos_token_id,
            **gen_kwargs
        )

    generated_ids = outputs[0][len(inputs.input_ids[0]):]
    return tokenizer.decode(generated_ids, skip_special_tokens=True)

In [7]:
mbpp_data = mbpp.get_dataset()["test"]
test_sample = mbpp_data[0]

prompt_data = mbpp.build_prompt(test_sample, tokenizer, train=False)
test_prompt = prompt_data["text"]

print("="*40)
print("ВХОДНОЙ ПРОМПТ:")
print(test_prompt)
print("="*40)

# Запускаем проверку
result = quick_sanity_check(model, tokenizer, test_prompt)

print("\n" + "="*40)
print("🤖 ОТВЕТ МОДЕЛИ:")
print("="*40)
print(result)

========================================
ВХОДНОЙ ПРОМПТ:
<|im_start|>system
You are an expert Python coding assistant. Given a problem description and function signature, implement the function body so that it passes all tests.<|im_end|>
<|im_start|>user
Problem:
Write a python function to remove first and last occurrence of a given character from the string.

Use the following function signature:
def remove_Occ(s,ch):

Write the full Python function implementation. Do NOT change the function name or arguments. You must analyze the problem in a <think> block first, then provide the solution. The code must be wrapped in markdown block.<|im_end|>
<|im_start|>assistant

========================================
🧐 Проверяем промпт: <|im_start|>system
You are an expert Python coding...

========================================
🤖 ОТВЕТ МОДЕЛИ:
========================================
<think>
Okay, I need to write a Python function called remove_Occ that takes a string s and a character ch. The task is to remove the first and last occurrence of the given character from the string. Let me think about how to approach this.

First, I remember that in Python, strings are immutable, so I can't modify them in place. So, I'll need to create a new string. How do I find the first and last occurrences?

For the first occurrence, I can use the string's find method. Like, s.find(ch) gives the index of the first occurrence. Then, I can take that index and slice the string from that index to the end. Wait, but if the character is not present, maybe I should check that, but the problem says to remove the first and last occurrence, so maybe the input string has the character, so I can just proceed.

Wait, the function is supposed to remove both the first and last occurrence. So, after finding the first occurrence, I need to remove that, then find the last occurrence and remove that. So steps:

1. Find the first index using s.find(ch).
2. Remove that index, then do the same for the last occurrence.

Wait, but how do I get the last occurrence? The same approach as the first. So, after finding the first, take the string from that index to the end. Then, find the last occurrence, and remove that.

So, for example, if the string is "hello", and the character is 'l', the first occurrence is index 2. So the new string is "hel", then the last occurrence is index 2, so remove that. So the new string is "hel".

Wait, but if the character is not present, then after finding the first occurrence, maybe the first occurrence is not present, so the string is the same as before. So, for example, if the input is "abc", and the character is 'a', then the first occurrence is index 0, then the last occurrence is index 0, so the string remains the same.

So, the process would be:

- Find the first occurrence: first_idx = s.find(ch)
- Remove first_idx from s, then do the same for the last occurrence.

But how to do that in Python. For example, after finding the first occurrence, we can use slicing: s[:first_idx] + s[first_idx+1:].

Then, after that, do the same for the last occurrence. So, after the first removal, we need to find the last occurrence again. So, last_idx = s.rfind(ch). Then, remove that index.

Wait, but the original string might have the same character in the first and last positions. So, for example, if the string is "apple", and the character is 'p', then the first occurrence is index 2, the last is index 0. So after removing first, the string is "app", then remove last, which is index 0, so the string becomes "p".

So, the steps are:

1. Find first occurrence: first_idx = s.find(ch)
2. Remove first_idx from s, then do the same for the last occurrence.

So, the function can be written as:

def remove_Occ(s, ch):
    first_idx = s.find(ch)
    s = s[:first_idx] + s[first_idx+1:]
    last_idx = s.rfind(ch)
    s = s[:last_idx] + s[last_idx+1:]

But wait, what if the first occurrence is at the end? Like, if the string is "abc" and the character is 'a', then first_idx is 0, remove that, then find the last occurrence, which is 0 again. So the string would be "abc" again.

But in this case, the code would do:

s = s[:0] + s[1:] => s is "bc".

Then, s.rfind(ch) would be 0, so s becomes "bc".

So, the code would work.

So, putting it all together. The function is supposed to return the modified string. So, the function can return s.

Wait, but the problem says to remove first and last occurrence. So, after removing the first, then remove the last. So the code above does that.

But what if the character is not present in the string? For example, if the input is "abc" and the character is 'd', then first_idx is -1, so s[:first_idx] is empty string, then the last_idx is -1. So the code would do s[: -1] + s[1:], which is "abc". Then, the code would remove the first and last occurrence, but since they don't exist, the string remains the same.

So, the code should handle that.

So the code is:

def remove_Occ(s, ch):
    first_idx = s.find(ch)
    s = s[:first_idx] + s[first_idx+1:]
    last_idx = s.rfind(ch)
    s = s[:last_idx] + s[last_idx+1:]

But wait, in Python, when you do s.find(ch), if the character is not present, it returns -1. Then, the code would process that. For example, if the first occurrence is not found, then first_idx is -1. So, when we take s[:first_idx], that's the entire string, then s[first_idx+1:] is the rest, which would be the same as s[0:], which is the entire string.

So, the code would work.

But the problem says to remove first and last occurrence, so after removing first, then remove last. So the code is correct.

So, the function should return the modified string.

Testing this with some examples:

Test case 1: s = "hello", ch = 'l'. First occurrence is 2. After removing first, the string becomes "hel". Then find last occurrence, which is 2. So remove that, the string becomes "hel".

Another example: s = "apple", ch = 'p'. First occurrence is 2. Remove, string becomes "app". Last occurrence is 0. Remove, string becomes "p".

Another example: s = "ab", ch = 'a'. First occurrence is 0. Remove, string becomes "b". Last occurrence is 0. Remove, string becomes "b".

So, the code should handle these cases.

Thus, the function is correct.
</think>

```python
def remove_Occ(s, ch):
    first_idx = s.find(ch)
    s = s[:first_idx] + s[first_idx+1:]
    last_idx = s.rfind(ch)
    s = s[:last_idx] + s[last_idx+1:]
    return s
```